wandb_version: 1

dataset:
  desc: null
  value: results/gemma-7b-it-apps_interview_207.jsonl
classifier:
  desc: null
  value: LR
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712155201.0
    t:
      1:
      - 1
      - 5
      - 33
      - 53
      - 55
      - 95
      2:
      - 1
      - 5
      - 33
      - 53
      - 55
      - 95
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.10.11
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
