wandb_version: 1

dataset:
  desc: null
  value: results/gemma-7b-it-apps_competition_207.jsonl
classifier:
  desc: null
  value: SVM
max_features:
  desc: null
  value: 1000
kernel:
  desc: null
  value: linear
vectorizer:
  desc: null
  value: TfidfVectorizer
ngram_range:
  desc: null
  value:
  - 1
  - 4
hide_comments:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712046132.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.10.11
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
